import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/common/navbar/Navbar.component";
import FooterComponent from "@/components/common/Footer/Footer.component";
import BottomNavComponent from "@/components/common/BottomNav/BottomNav.component";
import { InriaSerif } from "@/utils/fonts";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${InriaSerif.variable}`}>
        <NavbarComponent />
        {children}
        <FooterComponent />
        <BottomNavComponent />
      </body>
    </html>
  );
}
